### ISSUE TITLE
Shorter help message

### ISSUE THREAD

**Issue by EliuX** [TwilioDevEd/notifier-node#4]
"Help me" is the current command to request for help, but if its analyzed as a command `Help` would be the command and me would be a parameter, which may be redundant if it wont be used for nothing more. And its more intuitive having a command in lowercase. It may be like the regular `help` parameter:

Text your Twilio number for help:

```
  help
```

**Comment by EliuX** [comment]
Also the verb `suscribe` to `subscribe` to avoid typos

**Comment by mcelicalderon** [comment]
That was the original idea, but the words `help`, `unsubscribe` and `subscribe` are reserved by Twilio

**Comment by acamino** [comment]
Thanks guys.

@EliuX I strongly recommend you to read this https://www.twilio.com/help/faq/short-codes/what-are-the-requirements-for-short-code-help-and-stop-messages hopefully this article will dispel your concerns.
