### ISSUE TITLE
Notification_SID?

### ISSUE THREAD

**Issue by okcjosh** [TwilioDevEd/notifier-node#7]
The link in read_me for the notification service SID does not work. Upon more exploration it shows that this is in Beta release and normal users cannot access 'notification' service? 

Doesn't this pretty much render your app unusable?

**Comment by acamino** [comment]
Hey @okcjosh! You right, this feature is still in _Preview_, nonetheless you can request access to Notifier [here](https://www.twilio.com/notify). When you got access to the Notifier feature you can use this implementation.

Thanks for the feedback and sorry for the late response.
